Revert "cpp: add forward declaration to fix warning"
This reverts commit cad774932cd9656e5f7744357e79ea97e2fe0de7.

lead to compilation error on Mac OS X:

In file included from Elektra/src/plugins/struct/checker.hpp:19:
../src/bindings/cpp/include/key.hpp:1757:8: error: explicit specialization of non-template struct 'hash'
struct hash<kdb::Key>
       ^   ~~~~~~~~~~
../src/bindings/cpp/include/key.hpp:1757:8: error: redefinition of 'hash' as different kind of symbol
../src/bindings/cpp/include/key.hpp:1751:8: note: previous definition is here
struct hash;
       ^
2 errors generated.