dot cleanup to NO, because of strange bug:
(happend sometimes on build server)

Error: dot: can't open
/var/lib/jenkins/jobs/elektra-gcc44-all/workspace/build/doc/html/struct__Backend__coll__graph.dot
Problems running dot: exit code=2, command='dot',
	 arguments='"/var/lib/jenkins/jobs/elektra-gcc44-all/workspace/build/doc/html/struct__Backend__coll__graph.dot"
	 -Tcmapx -o
	 "/var/lib/jenkins/jobs/elektra-gcc44-all/workspace/build/doc/html/struct__Backend__coll__graph.map"'